name: Update Languages

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-languages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch languages
      run: |
        python fetch_languages.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update languages"
        git push